# GTI770 - Systèmes Intelligents et Apprentissage Machine

#### Alessandro L. Koerich

## Notebook Jupyter - 4a_Evaluation_Simpsons

# Simpsons Dataset

##### January 2019

In [1]:
# Imports General
import numpy as np
import matplotlib.pyplot as plt
import os
import sys
import time
        

In [2]:
# Imports Scikit-Learn
from sklearn.utils import shuffle
#from sklearn.cross_validation import train_test_split
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import normalize
from sklearn.preprocessing import scale
from sklearn.preprocessing import MinMaxScaler

In [3]:
#Imports from TP1 GTI770-H2018
import csv
import math
import scipy.ndimage as nd
from scipy.stats.mstats import mquantiles, kurtosis, skew
from sklearn.preprocessing import LabelEncoder

In [4]:
# Load data from file
# File with 4 features extracted from Simpsons
num_features = 4
data_train = np.loadtxt("simpsons_train_4features.csv", delimiter=",")

In [5]:
data_train

array([[6.88610189e-02, 6.03634074e-01, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [3.65637657e-02, 6.63399415e-01, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [5.38060897e-02, 6.32868590e-01, 0.00000000e+00, 9.90384615e-03,
        0.00000000e+00],
       ...,
       [0.00000000e+00, 4.40221530e-01, 0.00000000e+00, 0.00000000e+00,
        7.00000000e+00],
       [0.00000000e+00, 4.00426198e-01, 0.00000000e+00, 0.00000000e+00,
        7.00000000e+00],
       [0.00000000e+00, 2.99239039e-01, 0.00000000e+00, 6.28095181e-04,
        7.00000000e+00]])

In [11]:
# Define the training set
X_train  = data_train[:,0:num_features]
Y_train  = data_train[:,num_features]

In [12]:
X_train

array([[6.88610189e-02, 6.03634074e-01, 0.00000000e+00, 0.00000000e+00],
       [3.65637657e-02, 6.63399415e-01, 0.00000000e+00, 0.00000000e+00],
       [5.38060897e-02, 6.32868590e-01, 0.00000000e+00, 9.90384615e-03],
       ...,
       [0.00000000e+00, 4.40221530e-01, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 4.00426198e-01, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 2.99239039e-01, 0.00000000e+00, 6.28095181e-04]])

In [13]:
Y_train

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3.